In [ ]:
!pip install np_utils
!pip install tensorflow-gpu

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for np_utils: filename=np_utils-0.6.0-py3-none-any.whl size=56439 sha256=8e5f1dbfb9b77301504ad4e77590dea420021339e3ad64faeb443b5e2689b19c
  Stored in directory: /root/.cache/pip/wheels/b6/c7/50/2307607f44366dd021209f660045f8d51cb976514d30be7cc7
Successfully built np_utils
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
from keras.utils import to_categorical

In [ ]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())


[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 7887937171175726508
xla_global_id: -1
]


In [ ]:
# #importing libraries
from tensorflow.keras import regularizers
import tensorflow as tf

import tensorflow_datasets as tfds

# # #tf.enable_eager_execution()
from keras.layers import Dense, Activation, Dropout, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.optimizers import Adam
import np_utils
from keras.models import Sequential
# # from keras.preprocessing.image import ImageDataGenerator
# # # from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn import metrics
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
# # # import matplotlib.image as mpimg
# # # import matplotlib.pyplot as plt
import numpy as np
import os
import cv2
import random
from random import sample
from numpy import *
# # from PIL import Image

# # #import theano

In [ ]:
#Prepare Dataset for Training
path_train = "/content/drive/MyDrive/IP/image_train_test/train"
CATEGORIES = ["agreeableness","conscientiousness","extraversion","neuroticism","openness"]
#print(img_array.shape)
#new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
IMG_SIZE =200
training = []

#folder_path = "path/to/folder"
#num_files = 5  # specify the number of files to select

# all_files = os.listdir(folder_path)
# random_files = random.sample(all_files, num_files)

# print("Randomly selected files:")
# for file in random_files:
#     print(os.path.join(folder_path, file))


def createTrainingData():
  for category in CATEGORIES:
    path = os.path.join(path_train, category)
    class_num = CATEGORIES.index(category)
    num_files = 200  # specify the number of files to select
    all_files = os.listdir(path)
    random_files = sample(all_files, num_files)
    j=1
    for img in random_files:
      if j<=200:
        img_array = cv2.imread(os.path.join(path,img))
        new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
        training.append([new_array, class_num])
        j+=1
        print(j)

createTrainingData()


In [ ]:
#Prepare Dataset for Testing
path_test = "/content/drive/MyDrive/IP/image_train_test/test"
#CATEGORIES = ["agreeableness","conscientiousness","extraversion","neuroticism","openness"]
#print(img_array.shape)
#new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
#IMG_SIZE =200
testing = []
def createTestingData():
  for category in CATEGORIES:
    path = os.path.join(path_test, category)
    class_num = CATEGORIES.index(category)
    num_files = 60  # specify the number of files to select
    all_files = os.listdir(path)
    random_files = sample(all_files, num_files)
    j=1
    for img in random_files:   #os.listdir(path)
      if j<=60:
        img_array = cv2.imread(os.path.join(path,img))
        new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
        testing.append([new_array, class_num])
        j+=1
        print(j)
createTestingData()

In [ ]:
len(training)

1000

In [ ]:
len(testing)

300

In [ ]:
#Shuffle the Training Dataset
random.shuffle(training)

In [ ]:
#Shuffle the Testing Dataset
random.shuffle(testing)

In [ ]:
#Assigning Labels and Features for training dataset
X_train =[]
y_train =[]
for features, label in training:
  X_train.append(features)
  y_train.append(label)


In [ ]:
X_train = np.array(X_train).reshape(-1, IMG_SIZE, IMG_SIZE, 3)

In [ ]:
#Assigning Labels and Features for Testing dataset
X_test =[]
y_test =[]
for features, label in testing:
  X_test.append(features)
  y_test.append(label)

In [ ]:
X_test = np.array(X_test).reshape(-1, IMG_SIZE, IMG_SIZE, 3)

In [ ]:
#Normalising X and converting labels to categorical data for Training Dataset
X_train = X_train.astype('float32')
X_train /= 255

#X_train = (X_train / 255.0).astype('float16')


# # create a data generator for image normalization
# datagen = ImageDataGenerator(rescale=1./255)

# # fit the data generator on the training data
# datagen.fit(X_train)

# # use the data generator to normalize the training data in batches
# X_train = datagen.flow(X_train, batch_size=32)


In [ ]:
# from keras.utils import np_utils
Y_train = to_categorical(y_train, 5)
print(Y_train[100])
print(shape(Y_train))

[0. 0. 0. 0. 1.]
(1000, 5)


In [ ]:
#Normalising X and converting labels to categorical data for Testing Dataset
X_test = X_test.astype('float32')
X_test /= 255

#X_test = (X_test / 255.0).astype('float16')

# # create a data generator for image normalization
# datagen = ImageDataGenerator(rescale=1./255)

# # fit the data generator on the training data
# datagen.fit(X_test)

# # use the data generator to normalize the training data in batches
# X_test = datagen.flow(X_test, batch_size=32)


In [ ]:
# from keras.utils import np_utils
Y_test = to_categorical(y_test, 5)
print(Y_test[33])
print(shape(Y_test))

[0. 0. 0. 0. 1.]
(300, 5)


In [ ]:
print(Y_test[1])

[0. 0. 0. 0. 1.]


In [ ]:
batch_size = 16
nb_classes = 5
nb_epochs = 10
img_rows, img_columns = 200, 200
img_channel = 3
nb_filters = 32
nb_pool = 2
nb_conv = 3



In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), padding='same', activation=tf.nn.relu,
                           input_shape=(200, 200, 3)),
    tf.keras.layers.MaxPooling2D((2, 2), strides=2),
    tf.keras.layers.Conv2D(32, (3,3), padding='same', activation=tf.nn.relu),
    tf.keras.layers.MaxPooling2D((2, 2), strides=2),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation=tf.nn.relu,kernel_regularizer=regularizers.l2(0.01)),
    tf.keras.layers.Dense(5,  activation=tf.nn.softmax)
])
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(X_train, Y_train, batch_size = batch_size, epochs = nb_epochs, verbose = 1, validation_data = (X_test, Y_test))

In [ ]:
# from tensorflow.keras.applications import ResNet50
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, GlobalAveragePooling2D

# base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(200, 200, 3))

# model = Sequential([
#     base_model,
#     GlobalAveragePooling2D(),
#     Dense(128, activation='relu'),
#     Dense(5, activation='softmax')
# ])

# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, BatchNormalization, Dropout

# # Model architecture
# model = Sequential([
#     # Convolutional layers
#     Conv2D(32, (3, 3), activation='relu', input_shape=(200, 200, 3)),
#     BatchNormalization(),
#     MaxPooling2D(pool_size=(2, 2)),

#     Conv2D(64, (3, 3), activation='relu'),
#     BatchNormalization(),
#     MaxPooling2D(pool_size=(2, 2)),

#     Conv2D(128, (3, 3), activation='relu'),
#     BatchNormalization(),
#     MaxPooling2D(pool_size=(2, 2)),

#     # Flatten layer
#     Flatten(),

#     # Dense (fully connected) layers
#     Dense(256, activation='relu'),
#     BatchNormalization(),
#     Dropout(0.5),

#     Dense(128, activation='relu'),
#     BatchNormalization(),
#     Dropout(0.5),

#     # Output layer
#     Dense(5, activation='softmax')
# ])

# # Model compilation
# model.compile(optimizer='adam',
#               loss='categorical_crossentropy',
#               metrics=['accuracy'])

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, BatchNormalization, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers

# Model architecture
model = Sequential([
    # Convolutional layers
    Conv2D(32, (3, 3), activation='relu', input_shape=(200, 200, 3)),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2, 2)),

    Conv2D(64, (3, 3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2, 2)),

    Conv2D(128, (3, 3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2, 2)),

    # Flatten layer
    Flatten(),

    # Dense (fully connected) layers with dropout and L2 regularization
    Dense(256, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    BatchNormalization(),
    Dropout(0.5),

    Dense(128, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    BatchNormalization(),
    Dropout(0.5),

    # Output layer
    Dense(5, activation='softmax')
])

# Model compilation
model.compile(optimizer=Adam(learning_rate=0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Display the model summary
model.summary()




Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 198, 198, 32)      896       
                                                                 
 batch_normalization_10 (Ba  (None, 198, 198, 32)      128       
 tchNormalization)                                               
                                                                 
 max_pooling2d_6 (MaxPoolin  (None, 99, 99, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_7 (Conv2D)           (None, 97, 97, 64)        18496     
                                                                 
 batch_normalization_11 (Ba  (None, 97, 97, 64)        256       
 tchNormalization)                                               
                                                      

In [ ]:
model.fit(X_train, Y_train,
          epochs=20,
          batch_size=32,
          validation_data=((X_test, Y_test)))


Epoch 1/20
32/32 [==============================] - 147s 4s/step - loss: 11.8154 - accuracy: 0.2350 - val_loss: 12.4742 - val_accuracy: 0.1867
Epoch 2/20
32/32 [==============================] - 137s 4s/step - loss: 11.2905 - accuracy: 0.3570 - val_loss: 10.9376 - val_accuracy: 0.2000
Epoch 3/20
32/32 [==============================] - 136s 4s/step - loss: 8.8555 - accuracy: 0.4640 - val_loss: 8.5260 - val_accuracy: 0.2000
Epoch 4/20
32/32 [==============================] - 137s 4s/step - loss: 7.5150 - accuracy: 0.5080 - val_loss: 8.3739 - val_accuracy: 0.2000
Epoch 5/20
32/32 [==============================] - 146s 5s/step - loss: 6.9684 - accuracy: 0.5030 - val_loss: 7.1632 - val_accuracy: 0.2000
Epoch 6/20
32/32 [==============================] - 137s 4s/step - loss: 6.0180 - accuracy: 0.5920 - val_loss: 6.6281 - val_accuracy: 0.2000
Epoch 7/20
32/32 [==============================] - 147s 5s/step - loss: 5.5026 - accuracy: 0.6550 - val_loss: 6.5915 - val_accuracy: 0.2167
Epoch 8/2

In [ ]:
score = model.evaluate(X_test, Y_test, verbose = 0 )
print("Test accuracy: ", score)

Test accuracy:  [1.2789645195007324, 0.8769999742507935]


In [ ]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

In [ ]:
print(predictions[1],Y_test[1])

[0. 0. 0. 0. 1.] [0. 0. 1. 0. 0.]


In [ ]:
predictions = model.predict(X_test)
predictions = to_categorical(predictions.argmax(axis=1), num_classes=5)
precision = precision_score(Y_test, predictions,average='weighted')
recall = recall_score(Y_test, predictions,average='weighted')
accuracy = accuracy_score(Y_test, predictions)

print("Precision:", precision)
print("Recall:", recall)
print("Accuracy:", accuracy)

Precision: 0.2641620037303491
Recall: 0.20666666666666667
Accuracy: 0.20666666666666667


In [ ]:
#

Y_test shape: (1000, 5)
Predictions shape: (1000, 5)


In [ ]:
# import pickle
# with open("/content/drive/MyDrive/IP/models/image_model.pkl", "wb") as f:
#     pickle.dump(model, f)

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 200, 200, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 100, 100, 32)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 100, 100, 32)      9248      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 50, 50, 32)       0         
 2D)                                                             
                                                                 
 dropout (Dropout)           (None, 50, 50, 32)        0         
                                                                 
 flatten (Flatten)           (None, 80000)             0

In [ ]:
model.save("/content/drive/MyDrive/IP/models/image_model.h5")